name: Github Action Workflow TEST

on:
  push:
    branches:
      - test
  repository_dispatch:
    types:
      - build-test
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    uses: ehornos/pruebaFE/.github/workflows/s3-deploy.yml@test
    with:
      CI_ENV: test
      CONTENTFUL_ENVIRONMENT: 'test'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_TEST }}
